server:
  port: 6060

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sales_managements_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      platform: mysql

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

jackson:
  serialization:
    INDENT_OUTPUT: true

logging:
  level:
    org.springframework: INFO
    com.cyngofokglobal.sales: DEBUG

app:
  jwt:
    secret: GlF9+V9R95J/IxPGqSSPxFgFddhSDWalZbQBTKVkCFo=
    expirationMs: 3600000
