server:
  port: 6060

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sales_management_db?useSSL=false&serverTimezone=UTC
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      platform: mysql

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html

  jackson:
    serialization:
      INDENT_OUTPUT: true

  logging:
    level:
      org.springframework: INFO
      com.cyngofokglobal.sales: DEBUG

app:
  jwt:
    secret: +neSRemZJh6gxnv+NgKW6olVdGiT84Sw1A32OpLJt/o=
    expirationMs: 3600000
